### ISSUE TITLE
Weird posiiton

### ISSUE THREAD

**Issue by romreed** [SimformSolutionsPvtLtd/flutter_showcaseview#139]
**Describe the bug**
I try show Showcase in showCupertinoModalBottomSheet but got weird position.

`void showNameModal(BuildContext context) {
    showCupertinoModalBottomSheet(
        expand: true,
        context: context,
        backgroundColor: mainBackgroundColor,
        builder: (contextModal) =>
            ShowCaseWidget(builder: Builder(builder: (context) {
              WidgetsBinding.instance!.addPostFrameCallback((_) {
                if (education.isEducationIndex == 9)
                  ShowCaseWidget.of(context)!.startShowCase([education.ten]);
              });
              return SingleChildScrollView(
                  child: SafeArea(
                    child: CustomModalBottomSheet(
                      title: 'myCompanies/add_company/company_name'.tr,
                      onAccept: () => navigation.back(context: context),
                      rightWidget: Showcase(
                        onTargetClick: () => showCasePress(context: context),
                        onToolTipClick: () => showCasePress(context: context),
                        disposeOnTap: true,
                        key: education.eleven,
                        title: 'education/saveName'.tr,
                        description: 'education/saveNameBody'.tr,
                        child: Icon(Icons.done, color: greenColor),
                      ),
                      child: Column(
                        children: [
                          Showcase(
                            onTargetClick: () => showCasePress(context: context),
                            onToolTipClick: () => showCasePress(context: context),
                            disposeOnTap: true,
                            key: education.ten,
                            title: 'education/name'.tr,
                            description: 'education/nameShortBody'.tr,
                            child: TextFieldBorderAll(
                              controller: shortNameCtrl,
                              label: 'myCompanies/add_company/short_name'.tr,
                            ),
                          ),
                          SizedBox(height: 22),
                          CustomTextArea(
                            controller: fullNameCtrl,
                            label: 'myCompanies/add_company/full_name'.tr,
                          ),
                        ],
                      ),
                    ),
                  ),
              );
            })));
}`

![Simulator Screen Shot - iPhone X - 2021-09-09 at 17 45 48](https://user-images.githubusercontent.com/16118227/132708261-9390d0ea-01a8-4a4a-ab7a-7e2580c860f8.png)
![Simulator Screen Shot - iPhone X - 2021-09-09 at 17 45 46](https://user-images.githubusercontent.com/16118227/132708264-271221d9-9b89-41c8-bb2b-f93b82022488.png)

**Comment by meetjanani** [comment]
@romreed  
Could you please share more information along with code snippet that you are using? So we can investigate more on this.   

As I tried to reproduce this issue by multiple way but somehow I was not able to reproduced it correctly. 

I tried with using of showModalBottomSheet  & modal_bottom_sheet (showCupertinoModalBottomSheet, Source: https://pub.dev/packages/modal_bottom_sheet)

**Comment by romreed** [comment]
@meetjanani  
`void showNameModal(BuildContext context, [bool isEducation = false]) {
    showCupertinoModalBottomSheet(
        context: context,
        expand: !isEducation,
        backgroundColor: mainBackgroundColor,
        builder: (contextModal) =>
            ShowCaseWidget(builder: Builder(builder: (context) {
              WidgetsBinding.instance!.addPostFrameCallback((_) {
                if (education.isEducationIndex == 40)
                  ShowCaseWidget.of(context)!
                      .startShowCase([education.billNine]);
              });

              return SingleChildScrollView(
                child: SafeArea(
                  child: CustomModalBottomSheet(
                    title: 'myCompanies/add_company/company_name'.tr,
                    onAccept: () => navigation.back(context: context),
                    rightWidget: Showcase(
                      onTargetClick: () => showCasePress(context: context),
                      onToolTipClick: () => showCasePress(context: context),
                      disposeOnTap: true,
                      key: education.billTen,
                      title: 'education/saveName'.tr,
                      description: 'education/saveNameBody'.tr,
                      child: Icon(Icons.done, color: greenColor),
                    ),
                    child: Column(
                      children: [
                        Showcase(
                          onTargetClick: () => showCasePress(context: context),
                          onToolTipClick: () => showCasePress(context: context),
                          disposeOnTap: true,
                          key: education.billNine,
                          title: 'education/name'.tr,
                          description: 'education/nameShortBody'.tr,
                          child: TextFieldBorderAll(
                            // initialValue: widget.id != null ? company?.shortName : null,
                            // controller: shortNameCtrl,
                            label: 'myCompanies/add_company/short_name'.tr,
                          ),
                        ),
                        SizedBox(height: 22),
                        CustomTextArea(
                          // initialValue:
                          // widget.id != null ? company?.fullName : null,
                          // controller: fullNameCtrl,
                          label: 'myCompanies/add_company/full_name'.tr,
                        ),
                      ],
                    ),
                  ),
                ),
              );
            }))).whenComplete(() {
      if (education.isEducationIndex == 42)
        ShowCaseWidget.of(context)!.startShowCase([education.billEleven]);
    });
  }`

**Comment by meetjanani** [comment]
@romreed 
Thank you for the informations. we are able to reproduce this issue. we will work on it and will update the progress over here.

**Comment by romreed** [comment]
Please add key after of before. It help show case after item or before item.
![Simulator Screen Shot - iPhone X - 2021-09-16 at 17 30 48](https://user-images.githubusercontent.com/16118227/133630862-f12c9ed6-eacf-4085-b58e-b652924e601a.png)

**Comment by ducpham-geekyants** [comment]
@meetjanani  
I used Showcase.withWidget with child in right position of screen. So showcase went like this when it showed up, 
![Screen Shot 2021-09-17 at 10 48 08](https://user-images.githubusercontent.com/88526087/133721069-fda9095b-3c00-4090-9777-f28ad67e9ffa.png)

**Comment by meetjanani-simformsolutions** [comment]
@ducpham-geekyants  
Could you please share more information along with code snippet that you are using with your parent widget? It will be helpful for us to identify root cause on this.

**Comment by meetjanani** [comment]
@ducpham-geekyants 
Could you please share more information along with code snippet that you are using with your parent widget? It will be helpful for us to identify root cause on this.

**Comment by ducpham-geekyants** [comment]
@meetjanani here it is

@override
  Widget build(BuildContext context) {
    final appTheme = AppTheme.of(context);
    return ShowCaseWidget(
      onStart: (index, key) {},
      onComplete: (index, key) {},
      builder: Builder(
        builder: (context) => Container(
          color: ColorConstants.white,
          padding: EdgeInsets.symmetric(
            horizontal: 64,
            vertical: 40,
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                mainAxisSize: MainAxisSize.min,
                children: [
                  Showcase.withWidget(
                    key: _notificationKey,
                    shapeBorder: CircleBorder(),
                    disableAnimation: true,
                    container: DesktopNotificationPage(
                      atSign: '',
                    ),
                    height: 64,
                    width: 64,
                    overlayPadding: EdgeInsets.all(8),
                    overlayColor: Colors.transparent,
                    overlayOpacity: 0.0,
                    child: Container(
                      height: 36,
                      width: 36,
                      child: RawMaterialButton(
                        shape: new CircleBorder(),
                        elevation: 0.0,
                        fillColor: appTheme.borderColor,
                        child: Icon(
                          Icons.notifications,
                          size: 20,
                          color: appTheme.primaryTextColor,
                        ),
                        onPressed: () async {
                          ShowCaseWidget.of(context)!.dismiss();
                          ShowCaseWidget.of(context)!
                              .startShowCase([_notificationKey]);
                        },
                      ),
                    ),
                  ),
                ],
              ),
              SizedBox(
                height: 16,
              ),
              Expanded(
                child: Container(),
              ),
            ],
          ),
        ),
      ),
    );
  }

**Comment by ducpham-geekyants** [comment]
@meetjanani here it is

```
@override
  Widget build(BuildContext context) {
    final appTheme = AppTheme.of(context);
    return ShowCaseWidget(
      onStart: (index, key) {},
      onComplete: (index, key) {},
      builder: Builder(
        builder: (context) => Container(
          color: ColorConstants.white,
          padding: EdgeInsets.symmetric(
            horizontal: 64,
            vertical: 40,
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                mainAxisSize: MainAxisSize.min,
                children: [
                  Showcase.withWidget(
                    key: _notificationKey,
                    shapeBorder: CircleBorder(),
                    disableAnimation: true,
                    container: DesktopNotificationPage(
                      atSign: '',
                    ),
                    height: 64,
                    width: 64,
                    overlayPadding: EdgeInsets.all(8),
                    overlayColor: Colors.transparent,
                    overlayOpacity: 0.0,
                    child: Container(
                      height: 36,
                      width: 36,
                      child: RawMaterialButton(
                        shape: new CircleBorder(),
                        elevation: 0.0,
                        fillColor: appTheme.borderColor,
                        child: Icon(
                          Icons.notifications,
                          size: 20,
                          color: appTheme.primaryTextColor,
                        ),
                        onPressed: () async {
                          ShowCaseWidget.of(context)!.dismiss();
                          ShowCaseWidget.of(context)!
                              .startShowCase([_notificationKey]);
                        },
                      ),
                    ),
                  ),
                ],
              ),
              SizedBox(
                height: 16,
              ),
              Expanded(
                child: Container(),
              ),
            ],
          ),
        ),
      ),
    );
  }
```

**Comment by meetjanani** [comment]
@ducpham-geekyants  We identified the reason of error that you are facing with your ShowCase widget.

in case of using `Showcase.withWidget` we have to pass 2 properly [ height, width ] of our controller custom widget those we are passing into `controller` property of  `Showcase.withWidget `

`Showcase.withWidget` (
container: DesktopNotificationPage( atSign: '', ), // here is your custom widget
                    height: `Width of your custom container widget,`
                    width: `Height of your custom container widget,`
)

**Comment by romreed** [comment]
@meetjanani my issue still in work?

**Comment by meetjanani** [comment]
@romreed  We have fixed your issue and we are going to raise PR for the same very soon.
I will notify here once new version is available with this fix.

**Comment by romreed** [comment]
@meetjanani nice. thank you and your team.

**Comment by romreed** [comment]
![Simulator Screen Shot - iPhone X - 2021-12-01 at 12 41 36](https://user-images.githubusercontent.com/16118227/144220103-129d4d46-0956-47c3-9f87-cf9b4bb35f5c.png)
![Simulator Screen Shot - iPhone X - 2021-12-01 at 12 41 38](https://user-images.githubusercontent.com/16118227/144220113-331b6ceb-7c39-4ed8-9cf9-6d467ff8c126.png)
still getting the error in the new version
